# -*- coding: utf-8 -*-
"""CCORgifcreator.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1A9v2phXo7EPBk8JDK9fWvdmr3wFkyWZJ
"""

import os
import requests
from bs4 import BeautifulSoup
from PIL import Image
from io import BytesIO
from google.colab import drive

# 1. Mount Google Drive
drive.mount('/content/drive')

# 2. Configuration
URL = "https://services.swpc.noaa.gov/images/animations/ccor1/"
OUTPUT_PATH = "/content/drive/My Drive/noaa_ccor1_animation.gif"

print("Scanning NOAA directory...")
response = requests.get(URL)
soup = BeautifulSoup(response.text, 'html.parser')

# Filter for timestamped .jpg files
img_names = [
    a['href'] for a in soup.find_all('a', href=True)
    if a['href'].endswith('.jpg') and 'latest' not in a['href']
]
img_names.sort()

# --- OPTIMIZATION 1: Frame Skipping ---
# Take every 5th image to reduce the total number of frames further
img_names = img_names[::5]

if not img_names:
    print("No images found. Please check the URL.")
else:
    print(f"Downloading, resizing, and optimizing {len(img_names)} images...")
    frames = []

    for name in img_names:
        img_url = URL + name
        try:
            # Download image directly into memory
            response = requests.get(img_url)
            img = Image.open(BytesIO(response.content))

            # --- OPTIMIZATION 2: Resize ---
            # Original is 1024x960. Halving it reduces pixel count by 75%
            img = img.resize((512, 480), Image.Resampling.LANCZOS)

            # --- OPTIMIZATION 3: Color Palette Reduction ---
            # Convert to a 128-color palette (default is 256) to save data
            img = img.convert('P', palette=Image.ADAPTIVE, colors=128)

            frames.append(img)
        except Exception as e:
            print(f"Skipping {name} due to error: {e}")

    # 4. Save and Compress GIF
    if frames:
        print("Compiling GIF... this may take a moment.")

        # --- OPTIMIZATION 4: PIL Optimization ---
        frames[0].save(
            OUTPUT_PATH,
            format='GIF',
            append_images=frames[1:],
            save_all=True,
            duration=100, # 10fps
            loop=0,
            optimize=True # Compresses unchanged pixels between frames
        )

        # Verify final file size
        file_size_mb = os.path.getsize(OUTPUT_PATH) / (1024 * 1024)
        print(f"✅ Success! GIF saved to: {OUTPUT_PATH}")
        print(f"📊 Final File Size: {file_size_mb:.2f} MB")

        if file_size_mb > 2.0:
            print("⚠️ Warning: File is still over 2 MB. Increase the frame skip (e.g., img_names[::5]).")
        else:
            print("🎉 Perfect! This file is small enough for your Google Apps Script.")
    else:
        print("No frames were processed.")